### ISSUE TITLE
Assign appearance to theme seems not working after v0.6.5

### ISSUE THREAD

**Issue by alisaycl96** [reflex-dev/reflex#4384]
**Describe the bug**
After we upgrade reflex to `v0.6.5`, appearance for theme doesn't work anymore.

**To Reproduce**
```
app = rx.App(theme=rx.theme(appearance="light"))
```

**Expected behavior**
Appearance can be assigned correctly for theme in rx.App.

**Specifics (please complete the following information):**
 - Python Version: v3.11.10
 - Reflex Version: v0.6.5
 - OS: MacOS
 - Browser (Optional): chrome

**Comment by lcastiglione** [comment]
I'm having the same problem and couldn't find a solution. Even in the official documentation, in the [themes](https://reflex.dev/docs/styling/theming/#overview) section, it still shows the configuration for version 0.6.4 and not for 0.6.5

**Comment by Lendemor** [comment]
> I'm having the same problem and couldn't find a solution. Even in the official documentation, in the [themes](https://reflex.dev/docs/styling/theming/#overview) section, it still shows the configuration for version 0.6.4 and not for 0.6.5

It's a bug so the documentation should not change. It'll still be used the same once we fixed the bug.

**Comment by lcastiglione** [comment]
> > I'm having the same problem and couldn't find a solution. Even in the official documentation, in the [themes](https://reflex.dev/docs/styling/theming/#overview) section, it still shows the configuration for version 0.6.4 and not for 0.6.5
> 
> It's a bug so the documentation should not change. It'll still be used the same once we fixed the bug.

Hi Lendemor! I thought the documentation needed to be updated to show a new way to define the parameters in rx.App. Thanks so much for the clarification! 🙌🏻🙌🏻🙌🏻

**Comment by dentro-innovation** [comment]
Not sure why this issue got closed, I still have the same issue on reflex 0.6.7

`appearance` prop in `rx.theme` doesn't have any effect.

**Comment by miketech** [comment]
Same here. appearance has no impact.
